TechLog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from solutions.sitemaps import StaticViewSitemap, SolutionSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'solutions': SolutionSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('solutions.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('comments/', views.CommentListCreate.as_view(), name='comment-view-create'),
    path('comments/<int:pk>/', views.CommentDestroy.as_view(), name='comment-destroy'),
    path('solutions/', views.SolutionListCreate.as_view(), name='solution-view-create'),
    path('solutions/<str:username>', views.UserSolutionsList.as_view(), name='user-solution-list'),
    path('solutions/<int:pk>/', views.SolutionRetrieveUpdateDestroy.as_view(), name='solution-update'),
]

solutions/urls.py
from django.urls import path
from . import views

app_name = 'solutions'

urlpatterns = [
    path('', views.solution_list, name='solution-list'),
    path('tags/', views.tag_list, name='tag-list'),
    path('solution/create/', views.solution_create, name='create'),
    path('<str:username>/<slug:slug>/', views.solution_detail, name='detail'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('reset_password/', views.login_view, name='reset_password'),
    path('gusest_browse/', views.login_view, name='guest_browse'),
    path('logout/', views.logout_view, name="logout"),
    path('<str:username>/', views.user_profile, name='user_profile'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.forms import ValidationError
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            # log in the user
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('solutions:solution-list')
        else:
            messages.error(request, "Invalid username or password")

    return render(request, 'users/techlog_login.html')

def signup_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirmpassword')

        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, e)
            return render(request, 'users/techlog_signup.html')

        # Password validating
        if password != confirm_password:
            messages.error(request, "Passwords do not match.")
            return render(request, 'users/techlog_signup.html')
        
        # Check if username/email already exists
        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already exists.")
            return render(request, 'users/techlog_signup.html')
        
        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already in use.")
            return render(request, 'users/techlog_signup.html')
        
        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()

        login(request, user)
        return redirect('solutions:solution-list')

    return render(request, 'users/techlog_signup.html')

def logout_view(request):
    logout(request)
    return redirect('solutions:solution-list')

def user_profile(request, username):
    # Pobierz użytkownika na podstawie nazwy użytkownika lub zwróć błąd 404
    user = get_object_or_404(User, username=username)
    
    # Renderuj stronę profilu użytkownika
    return render(request, 'users/user_profile.html', {'profile_user': user})

users/templates/users/techlog_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TechLog</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'users/media/favicon.ico' %}"/>
</head>
<body>
    <div class="container">
        <div class="overlay">
            <div id="logo">
                <h1 class="title">TECHLOG</h1>
                <p class="subtitle">cosmic problems, simple solutions</p>
            </div>
            <form class="login_form" method="post">
                {% csrf_token %}
                <input type="text" placeholder="Username" name="username" required>
                <input type="password" placeholder="Password" name="password" required>
                <div class="buttons">
                    <button type="submit" class="button1" id="login_button">Login</button>
                    <a href="{% url 'users:reset_password' %}" class="reset-link">Reset Password</a>                    
                </div>
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </form>
            <div class="buttons">
                <button class="button2" id="signup_button" onclick="location.href='{% url 'users:signup' %}'">Sign Up</button>
                <a href="{% url 'solutions:solution-list' %}" class="guest-link">Browse as a Guest</a>
            </div>
        </div>
    </div>
</body>
</html>

users/templates/users/techlog_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TechLog</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'users/media/favicon.ico' %}"/>
</head>
<body>
    <div class="container">
        <div class="overlay2">
            <div id="logo">
                <h1 class="title">TECHLOG</h1>
                <p class="subtitle">cosmic problems, simple solutions</p>
            </div>
            <form class="signup_form" method="post">
                {% csrf_token %}
                <input type="email" placeholder="E-mail" name="email" required>
                <input type="text" placeholder="Username" name="username" required>
                <input type="password" placeholder="Password" name="password" required>
                <input type="password" placeholder="Confirm password" name="confirmpassword" required>
                <div class="buttons">
                    <button class="button1" type="submit" id="signup_button">Signup</button>                
                </div>
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </form>
        </div>
    </div>
</body>
</html>

users/templates/users/user_profile.html
{% extends "layout.html" %}

{% block maincontent %}
<div class="profile_section">
    <img src="{{ '/media/user.png' }}" alt="profile_picture">
    <div class="profile_info">
        <h2>{{ profile_user.username }}</h2>
        <p>Joined {{ profile_user.date_joined }}</p>
    </div>
</div>
<h1 class="page-title" id="ptitle"></h1>
<div id="solutions" class="solutions-container">
<!-- Solutions will be dynamically injected here -->
</div>
{% endblock maincontent %}
{% block js %}
    <script>
        const username = window.location.pathname.split('/')[1];
        const apiBaseURL = `/api/solutions/${username}`;
        const solutionsContainer = document.getElementById('solutions');
        const siteTitle = document.getElementById('ptitle');

        const fetchSolutions = async () => {
            try {
                const response = await fetch(apiBaseURL);
                const solutions = await response.json();

                solutionsContainer.innerHTML = '';
                
                if (solutions.length === 0) {
                    // Jeśli użytkownik nie ma żadnych rozwiązań
                    solutionsContainer.innerHTML = `
                        <p>${username} has not published any solutions yet.</p>
                    `;
                } else {
                    solutions.forEach(solution => {
                        const solutionElement = document.createElement('div');
                        siteTitle.innerHTML = "{{ profile_user.username}}'s solutions"
                        solutionElement.className = 'solution-card';

                        solutionElement.innerHTML = `
                            <h2 class="solution-title">
                                <a href="/${solution.author}/${solution.slug}/" class="solution-link">${solution.title}</a>
                            </h2>
                            <p class="solution-date">Posted on: ${new Date(solution.published_date).toLocaleDateString()}</p>
                            <p class="solution-snippet">${solution.author}</p>
                            <p class="solution-snippet">${solution.snippet}</p>
                        `;
                        solutionsContainer.appendChild(solutionElement);
                    });
                }
            } catch (error) {
                console.error('Error fetching solutions:', error);
            }
        };

        fetchSolutions();
    </script>
{% endblock js %}