TechLog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from solutions.sitemaps import StaticViewSitemap, SolutionSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'solutions': SolutionSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('solutions.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('comments/', views.CommentListCreate.as_view(), name='comment-view-create'),
    path('comments/<int:pk>/', views.CommentDestroy.as_view(), name='comment-destroy'),
    path('solutions/', views.SolutionListCreate.as_view(), name='solution-view-create'),
    path('solutions/<str:username>', views.UserSolutionsList.as_view(), name='user-solution-list'),
    path('solutions/<int:pk>/', views.SolutionRetrieveUpdateDestroy.as_view(), name='solution-update'),
]

solutions/urls.py
from django.urls import path
from . import views

app_name = 'solutions'

urlpatterns = [
    path('', views.solution_list, name='solution-list'),
    path('tags/', views.tag_list, name='tag-list'),
    path('solution/create/', views.solution_create, name='create'),
    path('<str:username>/<slug:slug>/', views.solution_detail, name='detail'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('reset_password/', views.login_view, name='reset_password'),
    path('gusest_browse/', views.login_view, name='guest_browse'),
    path('logout/', views.logout_view, name="logout"),
    path('<str:username>/', views.user_profile, name='user_profile'),
]

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TechLog</title>
    <meta name="description" content="TechLog - Latest tech tips, guides, and solutions for everyday problems.">
    <meta name="robots" content="index, follow">
    <meta property="og:image" content="https://techlog.berzantas.com/static/solutions/media/favicon.ico">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:type" content="website">
    <meta property="og:title" content="TechLog">
    <meta property="og:description" content="TechLog offers the best tech guides and solutions for everyday issues.">
    <link rel="stylesheet" href="{% static 'solutions/css/style.css' %}">
    <link rel="icon" href="https://techlog.berzantas.com/static/solutions/media/favicon.ico">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3547488460887249" crossorigin="anonymous"></script>
</head>
<body>
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="navbar">
            <div class="logo">
                <a href="{% url 'solutions:solution-list' %}" class="logo-text">TECHLOG</a>
            </div>

            <form id="search-form" action="/" method="get">
                    <input type="text" name="q" placeholder="Search solutions..." id="search-input">
            </form>

            <div class="navbar-right">
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <img src="{{ '/media/user.png' }}" class="dropbtn">
                    <div class="dropdown-content">
                        <a href="/{{ request.user.username }}">Profile</a>
                        <a href="/logout/" method="post">Logout</a>
                    </div>
                </div>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-link auth-button">Login</a>
                    <a href="{% url 'users:signup' %}" class="nav-link signup-button">Sign up</a>
                {% endif %}
            </div>
        </nav>

        <div class="aside-main">
            <div class="aside-parent">
                <!-- Sidebar -->
                <aside class="sidebar">
                    <ul>
                        {% if user.is_authenticated %}
                        <li><a href="{%  url 'solutions:create' %}" class="solution_create">New Solution</a></li>
                        {% endif %}
                        <li><a href="{% url 'solutions:solution-list' %}">HOME</a></li>
                        <li><a href="{% url 'solutions:solution-list' %}">SOLUTIONS</a></li>
                        <li><a href="{% url 'solutions:tag-list' %}">TAGS</a></li>
                    </ul>
                </aside>
            </div>
            <!-- Main Content -->
            <main class="main-container">
                {% block maincontent %}
                {% endblock maincontent %}
            </main>
            <div class="aside-parent">
                <aside class="ads-container">
                        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3547488460887249"
                            crossorigin="anonymous"></script>
                        <!-- ad_box -->
                        <ins class="adsbygoogle ad_box"
                            style="display:block"
                            data-ad-client="ca-pub-3547488460887249"
                            data-ad-slot="5811613385"
                            data-ad-format="auto"
                            data-full-width-responsive="true"></ins>
                        <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                </aside>
            </div>
        </div>
        <footer class="footer">
            <p>&copy; 2024 TechLog - Cosmic Problems, Simple Solutions</p>
        </footer>
    
        {% block js %}
        {% endblock js %}
    </div>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "TechLog",
  "url": "https://techlog.berzantas.com",
  "logo": "https://techlog.berzantas.com/static/solutions/media/favicon.ico"
}
</script>
</body>
</html>